apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: master1
  labels:
    k8s-master: true
    k8s-worker: true
spec:
  interfaceName: eth0
  node: ip-10-0-0-10
  expectedIPs: ["10.0.0.10"]
---
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: worker1
  labels:
    k8s-worker: true
spec:
  interfaceName: eth0
  node: ip-10-0-0-11
  expectedIPs: ["10.0.0.11"]
---
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: worker2
  labels:
    k8s-worker: true
spec:
  interfaceName: eth0
  node: ip-10-0-0-12
  expectedIPs: ["10.0.0.12"]
---
