apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: pool1-ipv4-ippool
spec:
  blockSize: 28
  cidr: 10.50.0.0/24
  ipipMode: Never
  natOutgoing: true
  nodeSelector: all()

---

apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: pool2-ipv4-ippool
spec:
  blockSize: 28
  cidr: 10.50.1.0/24
  ipipMode: Never
  natOutgoing: true
  nodeSelector: all()

